<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net20;net30;net35;net40;net45;net461;net48;net8.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyTitle>FSMultimedia</AssemblyTitle>
    <Company>Febrer Software</Company>
    <Product>FSMultimedia</Product>
    <Copyright>Copyright © 2025 Febrer Software</Copyright>
    <Authors>Juan Carlos Febrer</Authors>
    <AssemblyVersion>1.0.0.0</AssemblyVersion>
    <FileVersion>1.0.0.0</FileVersion>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(SolutionDir)firma_FS_app.pfx</AssemblyOriginatorKeyFile>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>
  <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' != 'net'">
    <PackageReference Include="System.Windows.Extensions" Version="4.6.0" />
    <PackageReference Include="System.Speech" Version="5.0.0" />
    <PackageReference Include="System.Drawing.Common" Version="8.0.0" />
	<PackageReference Include="System.Memory" Version="4.6.0" />
	<PackageReference Include="System.Text.Json" Version="9.0.1" />
  </ItemGroup>
    <ItemGroup Condition="'$(TargetFramework.TrimEnd(`0123456789`))' == 'net'">
	    <Reference Include="System.Text.Json">
		    <HintPath>C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PublicAssemblies\System.Text.Json.dll</HintPath>
	    </Reference>
		<Reference Include="System.Memory">
			<HintPath>C:\Program Files\Microsoft Visual Studio\2022\Community\Common7\IDE\PublicAssemblies\System.Memory.dll</HintPath>
		</Reference>
    </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\FS.Core\FSLibrary\FSLibrary.csproj" />
  </ItemGroup>
</Project>