//
// This file was auto-generated by a tool.  Do not modify.
//
using System.Resources;
using System.Reflection;

[assembly: NeutralResourcesLanguageAttribute("es-ES" , UltimateResourceFallbackLocation.MainAssembly)]
[assembly: AssemblyTitleAttribute("FSPortalWPF")]
[assembly: AssemblyDescriptionAttribute("Portal WPF")]
[assembly: AssemblyCompanyAttribute("Febrer Software")]
