<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFrameworks>net20;net30;net35;net40;net45;net461;net48;net8.0</TargetFrameworks>
    <OutputType>Library</OutputType>
    <GenerateAssemblyInfo>true</GenerateAssemblyInfo>
    <AssemblyTitle>FSBarcode</AssemblyTitle>
    <Product>FSBarcode</Product>
    <Copyright>Copyright © 2025 Febrer Software</Copyright>
    <Authors>Juan Carlos Febrer</Authors>
    <AssemblyVersion>1.0.0</AssemblyVersion>
    <SignAssembly>True</SignAssembly>
    <AssemblyOriginatorKeyFile>$(SolutionDir)firma_FS_app.pfx</AssemblyOriginatorKeyFile>
    <Platforms>AnyCPU;x86;x64</Platforms>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Debug' ">
    <CheckForOverflowUnderflow>True</CheckForOverflowUnderflow>
  </PropertyGroup>
  <PropertyGroup Condition=" '$(Configuration)' == 'Release' ">
    <DebugType>None</DebugType>
  </PropertyGroup>
  
  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' == '.NETFramework'">
    <Reference Include="System.Drawing" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)' == 'net461' or '$(TargetFramework)' == 'net48'">
    <PackageReference Include="itext" Version="9.7.0" />
    <PackageReference Include="itext.pdfhtml" Version="6.3.3" />
    <PackageReference Include="itext.commons" Version="9.7.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.7.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="5.0.0" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="5.0.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFrameworkIdentifier)' != '.NETFramework'">
    <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
    <PackageReference Include="itext" Version="9.7.0" />
    <PackageReference Include="itext.pdfhtml" Version="6.3.3" />
    <PackageReference Include="itext.commons" Version="9.7.0" />
    <PackageReference Include="itext.bouncy-castle-adapter" Version="9.7.0" />
    <PackageReference Include="Microsoft.Extensions.Logging.Abstractions" Version="9.0.1" />
    <PackageReference Include="Microsoft.Extensions.Logging" Version="9.0.1" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\FS.Core\FSLibrary\FSLibrary.csproj" />
  </ItemGroup>
  <ItemGroup>
    <Reference Include="zxing">
      <HintPath>..\..\dll\zxing.dll</HintPath>
    </Reference>
  </ItemGroup>
  <ItemGroup>
    <Reference Update="System.Core">
      <RequiredTargetFramework>3.5</RequiredTargetFramework>
    </Reference>
  </ItemGroup>
</Project>