#if NETFRAMEWORK

using System;
using System.IO;
using System.Text;
// Referencias de SAP Crystal Reports
using CrystalDecisions.CrystalReports.Engine;
using CrystalDecisions.Shared;

namespace FSConvert
{
    public class ConvertRptToWindowsForms
    {
        private const double TwipsPerPixel = 15.0;

        /// <summary>
        /// Procesa un archivo .rpt y retorna el código C# completo que debe ir dentro de un archivo .Designer.cs
        /// </summary>
        public static string Convert(string rptFilePath, string namespaceName, string formName)
        {
            if (!File.Exists(rptFilePath))
            {
                throw new FileNotFoundException("El archivo de Crystal Reports especificado no existe.", rptFilePath);
            }

            StringBuilder sbDeclaraciones = new StringBuilder();
            StringBuilder sbInicializaciones = new StringBuilder();
            StringBuilder sbPropiedades = new StringBuilder();

            using (ReportDocument report = new ReportDocument())
            {
                try
                {
                    report.Load(rptFilePath);

                    // 1. Cabecera del archivo Designer de Windows Forms
                    sbInicializaciones.AppendLine($"        private void InitializeComponent()");
                    sbInicializaciones.AppendLine($"        {{");

                    // 2. Procesar las secciones del reporte principal y subinformes
                    int panelCounter = 1;
                    int controlCounter = 1;

                    GenerarCodigoSecciones(report, sbDeclaraciones, sbInicializaciones, ref panelCounter, ref controlCounter, isSubreport: false);

                    if (report.Subreports.Count > 0)
                    {
                        foreach (ReportDocument subreport in report.Subreports)
                        {
                            sbInicializaciones.AppendLine($"            // ==================================================");
                            sbInicializaciones.AppendLine($"            // SUBINFORME: {subreport.Name}");
                            sbInicializaciones.AppendLine($"            // ==================================================");
                            GenerarCodigoSecciones(subreport, sbDeclaraciones, sbInicializaciones, ref panelCounter, ref controlCounter, isSubreport: true);
                        }
                    }

                    // 3. Configuración final del contenedor/Formulario base
                    sbInicializaciones.AppendLine($"            // ");
                    sbInicializaciones.AppendLine($"            // {formName}");
                    sbInicializaciones.AppendLine($"            // ");
                    sbInicializaciones.AppendLine($"            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);");
                    sbInicializaciones.AppendLine($"            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;");
                    sbInicializaciones.AppendLine($"            this.ClientSize = new System.Drawing.Size(850, 600);");
                    sbInicializaciones.AppendLine($"            this.AutoScroll = true;");
                    sbInicializaciones.AppendLine($"            this.Name = \"{formName}\";");
                    sbInicializaciones.AppendLine($"            this.Text = \"Vista de Reporte Migrado - {formName}\";");
                    sbInicializaciones.AppendLine($"            this.ResumeLayout(false);");
                    sbInicializaciones.AppendLine($"        }}");

                    // 4. Ensanblar la estructura final de la clase parcial .Designer.cs
                    StringBuilder resultadoCompleto = new StringBuilder();
                    resultadoCompleto.AppendLine($"//------------------------------------------------------------------------------");
                    resultadoCompleto.AppendLine($"// <auto-generated>");
                    resultadoCompleto.AppendLine($"//     Código generado por el motor de migración automática FSConvert RPT to WinForms.");
                    resultadoCompleto.AppendLine($"// </auto-generated>");
                    resultadoCompleto.AppendLine($"//------------------------------------------------------------------------------\n");
                    resultadoCompleto.AppendLine($"namespace {namespaceName}");
                    resultadoCompleto.AppendLine($"{{");
                    resultadoCompleto.AppendLine($"    partial class {formName}");
                    resultadoCompleto.AppendLine($"    {{");
                    resultadoCompleto.AppendLine($"        private System.ComponentModel.IContainer components = null;\n");
                    resultadoCompleto.AppendLine($"        protected override void Dispose(bool disposing)");
                    resultadoCompleto.AppendLine($"        {{");
                    resultadoCompleto.AppendLine($"            if (disposing && (components != null)) components.Dispose();");
                    resultadoCompleto.AppendLine($"            base.Dispose(disposing);");
                    resultadoCompleto.AppendLine($"        }}\n");

                    // Inyectar el método InitializeComponent generado
                    resultadoCompleto.Append(sbInicializaciones.ToString());
                    resultadoCompleto.AppendLine();

                    // Inyectar la lista de declaraciones de campos en la parte inferior del archivo
                    resultadoCompleto.AppendLine("        #region Componentes de la Interfaz Gráfica Generados");
                    resultadoCompleto.Append(sbDeclaraciones.ToString());
                    resultadoCompleto.AppendLine("        #endregion");
                    resultadoCompleto.AppendLine($"    }}");
                    resultadoCompleto.AppendLine($"}}");

                    return resultadoCompleto.ToString();
                }
                catch (Exception ex)
                {
                    throw new Exception($"Error crítico en el proceso de generación para Windows Forms: {ex.Message}", ex);
                }
                finally
                {
                    report.Close();
                }
            }
        }

        /// <summary>
        /// Genera de forma imperativa las instrucciones de código C# para crear los controles equivalentes de Windows Forms.
        /// </summary>
        private static void GenerarCodigoSecciones(ReportDocument doc, StringBuilder sbDec, StringBuilder sbInit, ref int panelCounter, ref int controlCounter, bool isSubreport)
        {
            string tagAmbiente = isSubreport ? $"sub_{doc.Name}_" : "";

            foreach (Section section in doc.ReportDefinition.Sections)
            {
                string panelName = $"pnl_{tagAmbiente}Section_{panelCounter++}";
                double heightInPixels = section.Height / TwipsPerPixel;

                // 1. Declarar y crear el Panel contenedor para simular la Sección de Crystal
                sbDec.AppendLine($"        private System.Windows.Forms.Panel {panelName};");

                sbInit.AppendLine($"            // ");
                sbInit.AppendLine($"            // {panelName} (Sección original: {section.Name})");
                sbInit.AppendLine($"            // ");
                sbInit.AppendLine($"            this.{panelName} = new System.Windows.Forms.Panel();");
                sbInit.AppendLine($"            this.{panelName}.BorderStyle = System.Windows.Forms.BorderStyle.FixedSingle;");
                sbInit.AppendLine($"            this.{panelName}.Size = new System.Drawing.Size(800, {(int)heightInPixels});");
                sbInit.AppendLine($"            this.{panelName}.Dock = System.Windows.Forms.DockStyle.Top;"); // Apila las secciones ordenadamente hacia arriba
                sbInit.AppendLine($"            this.Controls.Add(this.{panelName});");
                sbInit.AppendLine($"            this.{panelName}.SuspendLayout();");

                // Lista temporal para almacenar los nombres de los controles hijos que añadiremos al panel al final
                StringBuilder sbControlesHijos = new StringBuilder();

                foreach (ReportObject obj in section.ReportObjects)
                {
                    double left = obj.Left / TwipsPerPixel;
                    double top = obj.Top / TwipsPerPixel;
                    double width = obj.Width / TwipsPerPixel;
                    double height = obj.Height / TwipsPerPixel;

                    string controlId = $"{tagAmbiente}ctrl_{controlCounter++}";

                    switch (obj.Kind)
                    {
                        case ReportObjectKind.TextObject:
                            var textObj = (TextObject)obj;
                            string labelName = $"lbl_Static_{controlId}";
                            // Escapamos comillas dobles para que el string de C# no se rompa
                            string textoLimpio = textObj.Text.Replace("\"", "\\\"");

                            sbDec.AppendLine($"        private System.Windows.Forms.Label {labelName};");

                            sbInit.AppendLine($"            this.{labelName} = new System.Windows.Forms.Label();");
                            sbInit.AppendLine($"            this.{labelName}.Text = \"{textoLimpio}\";");
                            sbInit.AppendLine($"            this.{labelName}.Location = new System.Drawing.Point({(int)left}, {(int)top});");
                            sbInit.AppendLine($"            this.{labelName}.Size = new System.Drawing.Size({(int)width}, {(int)height});");
                            sbInit.AppendLine($"            this.{labelName}.Font = new System.Drawing.Font(\"{textObj.Font.Name}\", {textObj.Font.Size:F0}F, {(textObj.Font.Bold ? "System.Drawing.FontStyle.Bold" : "System.Drawing.FontStyle.Regular")});");

                            sbControlesHijos.AppendLine($"            this.{panelName}.Controls.Add(this.{labelName});");
                            break;

                        case ReportObjectKind.FieldObject:
                            var fieldObj = (FieldObject)obj;
                            string txtName = $"txt_Data_{controlId}";

                            sbDec.AppendLine($"        private System.Windows.Forms.TextBox {txtName};");

                            sbInit.AppendLine($"            this.{txtName} = new System.Windows.Forms.TextBox();");
                            sbInit.AppendLine($"            this.{txtName}.Location = new System.Drawing.Point({(int)left}, {(int)top});");
                            sbInit.AppendLine($"            this.{txtName}.Size = new System.Drawing.Size({(int)width}, {(int)height});");
                            sbInit.AppendLine($"            this.{txtName}.ReadOnly = true;"); // Imita la naturaleza de solo lectura de un reporte
                            sbInit.AppendLine($"            this.{txtName}.Tag = \"{fieldObj.DataSource.Name}\";"); // Guardamos el origen en el Tag para el Data Binding posterior

                            sbControlesHijos.AppendLine($"            this.{panelName}.Controls.Add(this.{txtName});");
                            break;

                        case ReportObjectKind.LineObject:
                            // En WinForms no hay control 'Line' por defecto. Emulamos usando un Label ultra delgado con color de fondo
                            string lineName = $"line_Graphic_{controlId}";
                            sbDec.AppendLine($"        private System.Windows.Forms.Label {lineName};");

                            sbInit.AppendLine($"            this.{lineName} = new System.Windows.Forms.Label();");
                            sbInit.AppendLine($"            this.{lineName}.Location = new System.Drawing.Point({(int)left}, {(int)top});");
                            // Si el alto original es insignificante, asumimos que es una línea horizontal, sino vertical
                            int lineWidth = (int)width == 0 ? 2 : (int)width;
                            int lineHeight = (int)height == 0 ? 2 : (int)height;
                            sbInit.AppendLine($"            this.{lineName}.Size = new System.Drawing.Size({lineWidth}, {lineHeight});");
                            sbInit.AppendLine($"            this.{lineName}.BackColor = System.Drawing.Color.DarkGray;");

                            sbControlesHijos.AppendLine($"            this.{panelName}.Controls.Add(this.{lineName});");
                            break;

                        case ReportObjectKind.SubreportObject:
                            var subreportObj = (SubreportObject)obj;
                            string subreportPlaceholderName = $"subreport_Container_{controlId}";

                            // El contenedor de un subinforme en WinForms será otro panel especial dedicado
                            sbDec.AppendLine($"        private System.Windows.Forms.Panel {subreportPlaceholderName};");

                            sbInit.AppendLine($"            this.{subreportPlaceholderName} = new System.Windows.Forms.Panel();");
                            sbInit.AppendLine($"            this.{subreportPlaceholderName}.BorderStyle = System.Windows.Forms.BorderStyle.Fixed3D;");
                            sbInit.AppendLine($"            this.{subreportPlaceholderName}.Location = new System.Drawing.Point({(int)left}, {(int)top});");
                            sbInit.AppendLine($"            this.{subreportPlaceholderName}.Size = new System.Drawing.Size({(int)width}, {(int)height});");
                            sbInit.AppendLine($"            this.{subreportPlaceholderName}.BackColor = System.Drawing.Color.GhostWhite;");

                            sbControlesHijos.AppendLine($"            this.{panelName}.Controls.Add(this.{subreportPlaceholderName});");
                            break;
                    }
                }

                // Aplicar los controles al panel correspondiente y reanudar su Layout gráfico
                sbInit.Append(sbControlesHijos.ToString());
                sbInit.AppendLine($"            this.{panelName}.ResumeLayout(false);");
                sbInit.AppendLine($"            this.{panelName}.PerformLayout();");
            }
        }
    }
}

#endif