//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSTests.ServiceReference1 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://febrersoftware.com", ConfigurationName="ServiceReference1.PortalWSSoap")]
    public interface PortalWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento username del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Login", ReplyAction="*")]
        FSTests.ServiceReference1.LoginResponse Login(FSTests.ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Login", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.LoginResponse> LoginAsync(FSTests.ServiceReference1.LoginRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sUsuario del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/AddUser", ReplyAction="*")]
        FSTests.ServiceReference1.AddUserResponse AddUser(FSTests.ServiceReference1.AddUserRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/AddUser", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.AddUserResponse> AddUserAsync(FSTests.ServiceReference1.AddUserRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento NombreCompletoResult del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/NombreCompleto", ReplyAction="*")]
        FSTests.ServiceReference1.NombreCompletoResponse NombreCompleto(FSTests.ServiceReference1.NombreCompletoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/NombreCompleto", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.NombreCompletoResponse> NombreCompletoAsync(FSTests.ServiceReference1.NombreCompletoRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UsuarioIdResult del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/UsuarioId", ReplyAction="*")]
        FSTests.ServiceReference1.UsuarioIdResponse UsuarioId(FSTests.ServiceReference1.UsuarioIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/UsuarioId", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.UsuarioIdResponse> UsuarioIdAsync(FSTests.ServiceReference1.UsuarioIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sTo del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/SendMail", ReplyAction="*")]
        FSTests.ServiceReference1.SendMailResponse SendMail(FSTests.ServiceReference1.SendMailRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/SendMail", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.SendMailResponse> SendMailAsync(FSTests.ServiceReference1.SendMailRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Login", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.LoginRequestBody Body;
        
        public LoginRequest() {
        }
        
        public LoginRequest(FSTests.ServiceReference1.LoginRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class LoginRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string username;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string password;
        
        public LoginRequestBody() {
        }
        
        public LoginRequestBody(string username, string password) {
            this.username = username;
            this.password = password;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="LoginResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.LoginResponseBody Body;
        
        public LoginResponse() {
        }
        
        public LoginResponse(FSTests.ServiceReference1.LoginResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class LoginResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string LoginResult;
        
        public LoginResponseBody() {
        }
        
        public LoginResponseBody(string LoginResult) {
            this.LoginResult = LoginResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUser", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.AddUserRequestBody Body;
        
        public AddUserRequest() {
        }
        
        public AddUserRequest(FSTests.ServiceReference1.AddUserRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class AddUserRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sUsuario;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sEMail;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sNombre;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sApellido1;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sApellido2;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public int sBirthMonth;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public int sBirthDay;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public int sBirthYear;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public bool sNotifications;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public bool sNewsletter;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=10)]
        public int sCountryCode;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=11)]
        public bool sRemember;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=12)]
        public bool sGenderMale;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=13)]
        public bool sGenderFemale;
        
        public AddUserRequestBody() {
        }
        
        public AddUserRequestBody(string sUsuario, string sEMail, string sNombre, string sApellido1, string sApellido2, int sBirthMonth, int sBirthDay, int sBirthYear, bool sNotifications, bool sNewsletter, int sCountryCode, bool sRemember, bool sGenderMale, bool sGenderFemale) {
            this.sUsuario = sUsuario;
            this.sEMail = sEMail;
            this.sNombre = sNombre;
            this.sApellido1 = sApellido1;
            this.sApellido2 = sApellido2;
            this.sBirthMonth = sBirthMonth;
            this.sBirthDay = sBirthDay;
            this.sBirthYear = sBirthYear;
            this.sNotifications = sNotifications;
            this.sNewsletter = sNewsletter;
            this.sCountryCode = sCountryCode;
            this.sRemember = sRemember;
            this.sGenderMale = sGenderMale;
            this.sGenderFemale = sGenderFemale;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class AddUserResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="AddUserResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.AddUserResponseBody Body;
        
        public AddUserResponse() {
        }
        
        public AddUserResponse(FSTests.ServiceReference1.AddUserResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class AddUserResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string AddUserResult;
        
        public AddUserResponseBody() {
        }
        
        public AddUserResponseBody(string AddUserResult) {
            this.AddUserResult = AddUserResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NombreCompletoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NombreCompleto", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.NombreCompletoRequestBody Body;
        
        public NombreCompletoRequest() {
        }
        
        public NombreCompletoRequest(FSTests.ServiceReference1.NombreCompletoRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class NombreCompletoRequestBody {
        
        public NombreCompletoRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class NombreCompletoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="NombreCompletoResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.NombreCompletoResponseBody Body;
        
        public NombreCompletoResponse() {
        }
        
        public NombreCompletoResponse(FSTests.ServiceReference1.NombreCompletoResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class NombreCompletoResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string NombreCompletoResult;
        
        public NombreCompletoResponseBody() {
        }
        
        public NombreCompletoResponseBody(string NombreCompletoResult) {
            this.NombreCompletoResult = NombreCompletoResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioId", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.UsuarioIdRequestBody Body;
        
        public UsuarioIdRequest() {
        }
        
        public UsuarioIdRequest(FSTests.ServiceReference1.UsuarioIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UsuarioIdRequestBody {
        
        public UsuarioIdRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuarioIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuarioIdResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.UsuarioIdResponseBody Body;
        
        public UsuarioIdResponse() {
        }
        
        public UsuarioIdResponse(FSTests.ServiceReference1.UsuarioIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class UsuarioIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UsuarioIdResult;
        
        public UsuarioIdResponseBody() {
        }
        
        public UsuarioIdResponseBody(string UsuarioIdResult) {
            this.UsuarioIdResult = UsuarioIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMail", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.SendMailRequestBody Body;
        
        public SendMailRequest() {
        }
        
        public SendMailRequest(FSTests.ServiceReference1.SendMailRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class SendMailRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sTo;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string sSubject;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string sBody;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string sFrom;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string sFromName;
        
        public SendMailRequestBody() {
        }
        
        public SendMailRequestBody(string sTo, string sSubject, string sBody, string sFrom, string sFromName) {
            this.sTo = sTo;
            this.sSubject = sSubject;
            this.sBody = sBody;
            this.sFrom = sFrom;
            this.sFromName = sFromName;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SendMailResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SendMailResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference1.SendMailResponseBody Body;
        
        public SendMailResponse() {
        }
        
        public SendMailResponse(FSTests.ServiceReference1.SendMailResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class SendMailResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SendMailResult;
        
        public SendMailResponseBody() {
        }
        
        public SendMailResponseBody(string SendMailResult) {
            this.SendMailResult = SendMailResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PortalWSSoapChannel : FSTests.ServiceReference1.PortalWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PortalWSSoapClient : System.ServiceModel.ClientBase<FSTests.ServiceReference1.PortalWSSoap>, FSTests.ServiceReference1.PortalWSSoap {
        
        public PortalWSSoapClient() {
        }
        
        public PortalWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PortalWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PortalWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference1.LoginResponse FSTests.ServiceReference1.PortalWSSoap.Login(FSTests.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public string Login(string username, string password) {
            FSTests.ServiceReference1.LoginRequest inValue = new FSTests.ServiceReference1.LoginRequest();
            inValue.Body = new FSTests.ServiceReference1.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            FSTests.ServiceReference1.LoginResponse retVal = ((FSTests.ServiceReference1.PortalWSSoap)(this)).Login(inValue);
            return retVal.Body.LoginResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.LoginResponse> FSTests.ServiceReference1.PortalWSSoap.LoginAsync(FSTests.ServiceReference1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference1.LoginResponse> LoginAsync(string username, string password) {
            FSTests.ServiceReference1.LoginRequest inValue = new FSTests.ServiceReference1.LoginRequest();
            inValue.Body = new FSTests.ServiceReference1.LoginRequestBody();
            inValue.Body.username = username;
            inValue.Body.password = password;
            return ((FSTests.ServiceReference1.PortalWSSoap)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference1.AddUserResponse FSTests.ServiceReference1.PortalWSSoap.AddUser(FSTests.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUser(request);
        }
        
        public string AddUser(string sUsuario, string sEMail, string sNombre, string sApellido1, string sApellido2, int sBirthMonth, int sBirthDay, int sBirthYear, bool sNotifications, bool sNewsletter, int sCountryCode, bool sRemember, bool sGenderMale, bool sGenderFemale) {
            FSTests.ServiceReference1.AddUserRequest inValue = new FSTests.ServiceReference1.AddUserRequest();
            inValue.Body = new FSTests.ServiceReference1.AddUserRequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sEMail = sEMail;
            inValue.Body.sNombre = sNombre;
            inValue.Body.sApellido1 = sApellido1;
            inValue.Body.sApellido2 = sApellido2;
            inValue.Body.sBirthMonth = sBirthMonth;
            inValue.Body.sBirthDay = sBirthDay;
            inValue.Body.sBirthYear = sBirthYear;
            inValue.Body.sNotifications = sNotifications;
            inValue.Body.sNewsletter = sNewsletter;
            inValue.Body.sCountryCode = sCountryCode;
            inValue.Body.sRemember = sRemember;
            inValue.Body.sGenderMale = sGenderMale;
            inValue.Body.sGenderFemale = sGenderFemale;
            FSTests.ServiceReference1.AddUserResponse retVal = ((FSTests.ServiceReference1.PortalWSSoap)(this)).AddUser(inValue);
            return retVal.Body.AddUserResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.AddUserResponse> FSTests.ServiceReference1.PortalWSSoap.AddUserAsync(FSTests.ServiceReference1.AddUserRequest request) {
            return base.Channel.AddUserAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference1.AddUserResponse> AddUserAsync(string sUsuario, string sEMail, string sNombre, string sApellido1, string sApellido2, int sBirthMonth, int sBirthDay, int sBirthYear, bool sNotifications, bool sNewsletter, int sCountryCode, bool sRemember, bool sGenderMale, bool sGenderFemale) {
            FSTests.ServiceReference1.AddUserRequest inValue = new FSTests.ServiceReference1.AddUserRequest();
            inValue.Body = new FSTests.ServiceReference1.AddUserRequestBody();
            inValue.Body.sUsuario = sUsuario;
            inValue.Body.sEMail = sEMail;
            inValue.Body.sNombre = sNombre;
            inValue.Body.sApellido1 = sApellido1;
            inValue.Body.sApellido2 = sApellido2;
            inValue.Body.sBirthMonth = sBirthMonth;
            inValue.Body.sBirthDay = sBirthDay;
            inValue.Body.sBirthYear = sBirthYear;
            inValue.Body.sNotifications = sNotifications;
            inValue.Body.sNewsletter = sNewsletter;
            inValue.Body.sCountryCode = sCountryCode;
            inValue.Body.sRemember = sRemember;
            inValue.Body.sGenderMale = sGenderMale;
            inValue.Body.sGenderFemale = sGenderFemale;
            return ((FSTests.ServiceReference1.PortalWSSoap)(this)).AddUserAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference1.NombreCompletoResponse FSTests.ServiceReference1.PortalWSSoap.NombreCompleto(FSTests.ServiceReference1.NombreCompletoRequest request) {
            return base.Channel.NombreCompleto(request);
        }
        
        public string NombreCompleto() {
            FSTests.ServiceReference1.NombreCompletoRequest inValue = new FSTests.ServiceReference1.NombreCompletoRequest();
            inValue.Body = new FSTests.ServiceReference1.NombreCompletoRequestBody();
            FSTests.ServiceReference1.NombreCompletoResponse retVal = ((FSTests.ServiceReference1.PortalWSSoap)(this)).NombreCompleto(inValue);
            return retVal.Body.NombreCompletoResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.NombreCompletoResponse> FSTests.ServiceReference1.PortalWSSoap.NombreCompletoAsync(FSTests.ServiceReference1.NombreCompletoRequest request) {
            return base.Channel.NombreCompletoAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference1.NombreCompletoResponse> NombreCompletoAsync() {
            FSTests.ServiceReference1.NombreCompletoRequest inValue = new FSTests.ServiceReference1.NombreCompletoRequest();
            inValue.Body = new FSTests.ServiceReference1.NombreCompletoRequestBody();
            return ((FSTests.ServiceReference1.PortalWSSoap)(this)).NombreCompletoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference1.UsuarioIdResponse FSTests.ServiceReference1.PortalWSSoap.UsuarioId(FSTests.ServiceReference1.UsuarioIdRequest request) {
            return base.Channel.UsuarioId(request);
        }
        
        public string UsuarioId() {
            FSTests.ServiceReference1.UsuarioIdRequest inValue = new FSTests.ServiceReference1.UsuarioIdRequest();
            inValue.Body = new FSTests.ServiceReference1.UsuarioIdRequestBody();
            FSTests.ServiceReference1.UsuarioIdResponse retVal = ((FSTests.ServiceReference1.PortalWSSoap)(this)).UsuarioId(inValue);
            return retVal.Body.UsuarioIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.UsuarioIdResponse> FSTests.ServiceReference1.PortalWSSoap.UsuarioIdAsync(FSTests.ServiceReference1.UsuarioIdRequest request) {
            return base.Channel.UsuarioIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference1.UsuarioIdResponse> UsuarioIdAsync() {
            FSTests.ServiceReference1.UsuarioIdRequest inValue = new FSTests.ServiceReference1.UsuarioIdRequest();
            inValue.Body = new FSTests.ServiceReference1.UsuarioIdRequestBody();
            return ((FSTests.ServiceReference1.PortalWSSoap)(this)).UsuarioIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference1.SendMailResponse FSTests.ServiceReference1.PortalWSSoap.SendMail(FSTests.ServiceReference1.SendMailRequest request) {
            return base.Channel.SendMail(request);
        }
        
        public string SendMail(string sTo, string sSubject, string sBody, string sFrom, string sFromName) {
            FSTests.ServiceReference1.SendMailRequest inValue = new FSTests.ServiceReference1.SendMailRequest();
            inValue.Body = new FSTests.ServiceReference1.SendMailRequestBody();
            inValue.Body.sTo = sTo;
            inValue.Body.sSubject = sSubject;
            inValue.Body.sBody = sBody;
            inValue.Body.sFrom = sFrom;
            inValue.Body.sFromName = sFromName;
            FSTests.ServiceReference1.SendMailResponse retVal = ((FSTests.ServiceReference1.PortalWSSoap)(this)).SendMail(inValue);
            return retVal.Body.SendMailResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference1.SendMailResponse> FSTests.ServiceReference1.PortalWSSoap.SendMailAsync(FSTests.ServiceReference1.SendMailRequest request) {
            return base.Channel.SendMailAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference1.SendMailResponse> SendMailAsync(string sTo, string sSubject, string sBody, string sFrom, string sFromName) {
            FSTests.ServiceReference1.SendMailRequest inValue = new FSTests.ServiceReference1.SendMailRequest();
            inValue.Body = new FSTests.ServiceReference1.SendMailRequestBody();
            inValue.Body.sTo = sTo;
            inValue.Body.sSubject = sSubject;
            inValue.Body.sBody = sBody;
            inValue.Body.sFrom = sFrom;
            inValue.Body.sFromName = sFromName;
            return ((FSTests.ServiceReference1.PortalWSSoap)(this)).SendMailAsync(inValue);
        }
    }
}
