// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//     NOTE! Types in Cbc has been optimized away.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     http://FS.codeplex.com/
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace FS.Ubl2.Cbc
{
    
}
