// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
//
//     http://FS.codeplex.com/
//
// </auto-generated>
//------------------------------------------------------------------------------
namespace FSUbl.Qdt
{
    using FSUbl.Udt;
    
    
    /// <summary>
    ///  The set of possible reasons for an allowance or charge.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class AllowanceChargeReasonCodeType : CodeType
    {
        
        public static implicit operator AllowanceChargeReasonCodeType(System.String value)
        {
        	AllowanceChargeReasonCodeType ret = new AllowanceChargeReasonCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of possible ways in which communication can be made (eg. Phone, email, etc).
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class ChannelCodeType : CodeType
    {
        
        public static implicit operator ChannelCodeType(System.String value)
        {
        	ChannelCodeType ret = new ChannelCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  Distinction between CHIP and MAG STRIPE cards
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class ChipCodeType : CodeType
    {
        
        public static implicit operator ChipCodeType(System.String value)
        {
        	ChipCodeType ret = new ChipCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of code values for classifying series 1 freight containers based on external dimensions, associated ratings and, where appropriate, the minimum internal and door opening dimensions for certain types of containers.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class ContainerSizeTypeCodeType : CodeType
    {
        
        public static implicit operator ContainerSizeTypeCodeType(System.String value)
        {
        	ContainerSizeTypeCodeType ret = new ContainerSizeTypeCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of countries of the world.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class CountryIdentificationCodeType : CodeType
    {
        
        public static implicit operator CountryIdentificationCodeType(System.String value)
        {
        	CountryIdentificationCodeType ret = new CountryIdentificationCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of world currencies.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class CurrencyCodeType : CodeType
    {
        
        public static implicit operator CurrencyCodeType(System.String value)
        {
        	CurrencyCodeType ret = new CurrencyCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of possible statuses of a document with regard to its original state.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class DocumentStatusCodeType : CodeType
    {
        
        public static implicit operator DocumentStatusCodeType(System.String value)
        {
        	DocumentStatusCodeType ret = new DocumentStatusCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The possible directions of latitude
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class LatitudeDirectionCodeType : CodeType
    {
        
        public static implicit operator LatitudeDirectionCodeType(System.String value)
        {
        	LatitudeDirectionCodeType ret = new LatitudeDirectionCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of possible statuses of a line in a transaction with regard to its original state.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class LineStatusCodeType : CodeType
    {
        
        public static implicit operator LineStatusCodeType(System.String value)
        {
        	LineStatusCodeType ret = new LineStatusCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The possible directions of longitude
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class LongitudeDirectionCodeType : CodeType
    {
        
        public static implicit operator LongitudeDirectionCodeType(System.String value)
        {
        	LongitudeDirectionCodeType ret = new LongitudeDirectionCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of valid arithmetic operators
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class OperatorCodeType : CodeType
    {
        
        public static implicit operator OperatorCodeType(System.String value)
        {
        	OperatorCodeType ret = new OperatorCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of code values for Passengers, Types of Cargo, Packages and Packaging Materials (with Complementary Codes for Package Names)
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class PackagingTypeCodeType : CodeType
    {
        
        public static implicit operator PackagingTypeCodeType(System.String value)
        {
        	PackagingTypeCodeType ret = new PackagingTypeCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of valid means of paying the debt incurred.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class PaymentMeansCodeType : CodeType
    {
        
        public static implicit operator PaymentMeansCodeType(System.String value)
        {
        	PaymentMeansCodeType ret = new PaymentMeansCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of code values for Trade and Transport Locations
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class PortCodeType : CodeType
    {
        
        public static implicit operator PortCodeType(System.String value)
        {
        	PortCodeType ret = new PortCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of values that indicate the status of an OrderItem in relation to substitution, denoting an acceptable substitute in the Order, an original for which an alternative is offered in the Order Confirmation, or an original for which an actual replacement is advised in the Despatch Advice.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class SubstitutionStatusCodeType : CodeType
    {
        
        public static implicit operator SubstitutionStatusCodeType(System.String value)
        {
        	SubstitutionStatusCodeType ret = new SubstitutionStatusCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of code values for Trade and Transport Status
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class TransportationStatusCodeType : CodeType
    {
        
        public static implicit operator TransportationStatusCodeType(System.String value)
        {
        	TransportationStatusCodeType ret = new TransportationStatusCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of code values for qualifying a type of equipment used in the transportation of goods.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class TransportEquipmentTypeCodeType : CodeType
    {
        
        public static implicit operator TransportEquipmentTypeCodeType(System.String value)
        {
        	TransportEquipmentTypeCodeType ret = new TransportEquipmentTypeCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of code values for modes of transport
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class TransportModeCodeType : CodeType
    {
        
        public static implicit operator TransportModeCodeType(System.String value)
        {
        	TransportModeCodeType ret = new TransportModeCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
    
    /// <summary>
    ///  The set of code values for Units of Measure Used in International Trade
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("ublxsd", "2.0.0.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="urn:oasis:names:specification:ubl:schema:xsd:QualifiedDatatypes-2")]
    public partial class UnitOfMeasureCodeType : CodeType
    {
        
        public static implicit operator UnitOfMeasureCodeType(System.String value)
        {
        	UnitOfMeasureCodeType ret = new UnitOfMeasureCodeType();
        	ret.Value = value;
             return string.IsNullOrEmpty(value) ? null : ret;
        }
    }
}
