//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSAutomatizeWeb.Language {
    using System;
    
    
    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("FSAutomatizeWeb.Language.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a About.
        /// </summary>
        public static string About {
            get {
                return ResourceManager.GetString("About", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Web Automation software built with the aim to help users automate everyday tasks and work effectively.
        ///
        ///Contact: Đinh Công Thắng
        ///Phone: 0972424100
        ///Email: dinhcongthang113@gmail.com
        ///Dong A Bank Account: 596667.
        /// </summary>
        public static string AboutDescription {
            get {
                return ResourceManager.GetString("AboutDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account.
        /// </summary>
        public static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Account incorrect, please try again!.
        /// </summary>
        public static string AccountIncorrect {
            get {
                return ResourceManager.GetString("AccountIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new.
        /// </summary>
        public static string AddNew {
            get {
                return ResourceManager.GetString("AddNew", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Add new successful.
        /// </summary>
        public static string AddSuccess {
            get {
                return ResourceManager.GetString("AddSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Alert.
        /// </summary>
        public static string Alert {
            get {
                return ResourceManager.GetString("Alert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Attribute.
        /// </summary>
        public static string Attribute {
            get {
                return ResourceManager.GetString("Attribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a What do you want go get attribute?.
        /// </summary>
        public static string AttributeMessage {
            get {
                return ResourceManager.GetString("AttributeMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Auto Bot.
        /// </summary>
        public static string Autobot {
            get {
                return ResourceManager.GetString("Autobot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Back.
        /// </summary>
        public static string Back {
            get {
                return ResourceManager.GetString("Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a You have successfully minimized your form..
        /// </summary>
        public static string BallonTipText {
            get {
                return ResourceManager.GetString("BallonTipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Minimize to Tray App.
        /// </summary>
        public static string BallonTipTitle {
            get {
                return ResourceManager.GetString("BallonTipTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Button.
        /// </summary>
        public static string Button {
            get {
                return ResourceManager.GetString("Button", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Captcha Border.
        /// </summary>
        public static string CaptchaBorder {
            get {
                return ResourceManager.GetString("CaptchaBorder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Capture.
        /// </summary>
        public static string Capture {
            get {
                return ResourceManager.GetString("Capture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check Element.
        /// </summary>
        public static string CheckElement {
            get {
                return ResourceManager.GetString("CheckElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Check for Update.
        /// </summary>
        public static string CheckUpdate {
            get {
                return ResourceManager.GetString("CheckUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear.
        /// </summary>
        public static string Clear {
            get {
                return ResourceManager.GetString("Clear", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Clear Log.
        /// </summary>
        public static string ClearLog {
            get {
                return ResourceManager.GetString("ClearLog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click.
        /// </summary>
        public static string Click {
            get {
                return ResourceManager.GetString("Click", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Click Control.
        /// </summary>
        public static string ClickControl {
            get {
                return ResourceManager.GetString("ClickControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close All Tab.
        /// </summary>
        public static string CloseAllTab {
            get {
                return ResourceManager.GetString("CloseAllTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Close Tab.
        /// </summary>
        public static string CloseTab {
            get {
                return ResourceManager.GetString("CloseTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Code.
        /// </summary>
        public static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Color Element.
        /// </summary>
        public static string ColorElement {
            get {
                return ResourceManager.GetString("ColorElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Configs.
        /// </summary>
        public static string Configs {
            get {
                return ResourceManager.GetString("Configs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Confirm.
        /// </summary>
        public static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want go to website?.
        /// </summary>
        public static string ConfirmGoWebsite {
            get {
                return ResourceManager.GetString("ConfirmGoWebsite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter Confirm Password.
        /// </summary>
        public static string ConfirmRequrired {
            get {
                return ResourceManager.GetString("ConfirmRequrired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sleep until browser loaded?.
        /// </summary>
        public static string ConfirmSleep {
            get {
                return ResourceManager.GetString("ConfirmSleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Do you want to update new version?.
        /// </summary>
        public static string ConfirmUpdate {
            get {
                return ResourceManager.GetString("ConfirmUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Content.
        /// </summary>
        public static string Content {
            get {
                return ResourceManager.GetString("Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Convert.
        /// </summary>
        public static string Convert {
            get {
                return ResourceManager.GetString("Convert", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Copy Url To Clipboard.
        /// </summary>
        public static string CopyUrlToClipboard {
            get {
                return ResourceManager.GetString("CopyUrlToClipboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create.
        /// </summary>
        public static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create File.
        /// </summary>
        public static string CreateFile {
            get {
                return ResourceManager.GetString("CreateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Folder.
        /// </summary>
        public static string CreateFolder {
            get {
                return ResourceManager.GetString("CreateFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Create Task.
        /// </summary>
        public static string CreateTask {
            get {
                return ResourceManager.GetString("CreateTask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Current Path.
        /// </summary>
        public static string CurrentPath {
            get {
                return ResourceManager.GetString("CurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Database.
        /// </summary>
        public static string Database {
            get {
                return ResourceManager.GetString("Database", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete Completed.
        /// </summary>
        public static string DeleteCompleted {
            get {
                return ResourceManager.GetString("DeleteCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Are you sure to delete this item?.
        /// </summary>
        public static string DeleteConfirm {
            get {
                return ResourceManager.GetString("DeleteConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Delete successful.
        /// </summary>
        public static string DeleteSuccess {
            get {
                return ResourceManager.GetString("DeleteSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Descrypt.
        /// </summary>
        public static string Descypt {
            get {
                return ResourceManager.GetString("Descypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Developer Tools.
        /// </summary>
        public static string DeveloperTools {
            get {
                return ResourceManager.GetString("DeveloperTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Display.
        /// </summary>
        public static string Display {
            get {
                return ResourceManager.GetString("Display", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download.
        /// </summary>
        public static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Download website.
        /// </summary>
        public static string DownloadWebSite {
            get {
                return ResourceManager.GetString("DownloadWebSite", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Dropdown.
        /// </summary>
        public static string Dropdown {
            get {
                return ResourceManager.GetString("Dropdown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Element.
        /// </summary>
        public static string Element {
            get {
                return ResourceManager.GetString("Element", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Email already exists.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your Email not valid.
        /// </summary>
        public static string EmailNotValid {
            get {
                return ResourceManager.GetString("EmailNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your Email.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter URL.
        /// </summary>
        public static string EmptyUrl {
            get {
                return ResourceManager.GetString("EmptyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Encrypt.
        /// </summary>
        public static string Encrypt {
            get {
                return ResourceManager.GetString("Encrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a English.
        /// </summary>
        public static string English {
            get {
                return ResourceManager.GetString("English", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excel.
        /// </summary>
        public static string Excel {
            get {
                return ResourceManager.GetString("Excel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Excute Query.
        /// </summary>
        public static string ExcuteQuery {
            get {
                return ResourceManager.GetString("ExcuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute.
        /// </summary>
        public static string Execute {
            get {
                return ResourceManager.GetString("Execute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Execute Query.
        /// </summary>
        public static string ExecuteQuery {
            get {
                return ResourceManager.GetString("ExecuteQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Exit.
        /// </summary>
        public static string Exit {
            get {
                return ResourceManager.GetString("Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Explore.
        /// </summary>
        public static string Explore {
            get {
                return ResourceManager.GetString("Explore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Extract.
        /// </summary>
        public static string Extract {
            get {
                return ResourceManager.GetString("Extract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File.
        /// </summary>
        public static string File {
            get {
                return ResourceManager.GetString("File", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File Upload.
        /// </summary>
        public static string FileUpload {
            get {
                return ResourceManager.GetString("FileUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill.
        /// </summary>
        public static string Fill {
            get {
                return ResourceManager.GetString("Fill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill Dropdown List.
        /// </summary>
        public static string FillDropDownList {
            get {
                return ResourceManager.GetString("FillDropDownList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Fill iFrame.
        /// </summary>
        public static string FillIframe {
            get {
                return ResourceManager.GetString("FillIframe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Folder.
        /// </summary>
        public static string Folder {
            get {
                return ResourceManager.GetString("Folder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Force Log Off.
        /// </summary>
        public static string ForceLogOff {
            get {
                return ResourceManager.GetString("ForceLogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Web Automation.
        /// </summary>
        public static string FSAutomatizeWeb {
            get {
                return ResourceManager.GetString("FSAutomatizeWeb", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Generate Key.
        /// </summary>
        public static string GenerateKey {
            get {
                return ResourceManager.GetString("GenerateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Account.
        /// </summary>
        public static string GetAccount {
            get {
                return ResourceManager.GetString("GetAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Account By.
        /// </summary>
        public static string GetAccountBy {
            get {
                return ResourceManager.GetString("GetAccountBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Column.
        /// </summary>
        public static string GetColumn {
            get {
                return ResourceManager.GetString("GetColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Content.
        /// </summary>
        public static string GetCurrentContent {
            get {
                return ResourceManager.GetString("GetCurrentContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Current Login.
        /// </summary>
        public static string GetCurrentLogin {
            get {
                return ResourceManager.GetString("GetCurrentLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Current Mouse.
        /// </summary>
        public static string GetCurrentMouse {
            get {
                return ResourceManager.GetString("GetCurrentMouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Current Path.
        /// </summary>
        public static string GetCurrentPath {
            get {
                return ResourceManager.GetString("GetCurrentPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Current Url.
        /// </summary>
        public static string GetCurrentUrl {
            get {
                return ResourceManager.GetString("GetCurrentUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Database.
        /// </summary>
        public static string GetDatabase {
            get {
                return ResourceManager.GetString("GetDatabase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Files.
        /// </summary>
        public static string GetFiles {
            get {
                return ResourceManager.GetString("GetFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Folders.
        /// </summary>
        public static string GetFolders {
            get {
                return ResourceManager.GetString("GetFolders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Height.
        /// </summary>
        public static string GetHeight {
            get {
                return ResourceManager.GetString("GetHeight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Row.
        /// </summary>
        public static string GetRow {
            get {
                return ResourceManager.GetString("GetRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Table.
        /// </summary>
        public static string GetTable {
            get {
                return ResourceManager.GetString("GetTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Get Title.
        /// </summary>
        public static string GetTitle {
            get {
                return ResourceManager.GetString("GetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Go.
        /// </summary>
        public static string Go {
            get {
                return ResourceManager.GetString("Go", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Help.
        /// </summary>
        public static string Help {
            get {
                return ResourceManager.GetString("Help", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hibernate.
        /// </summary>
        public static string Hibernate {
            get {
                return ResourceManager.GetString("Hibernate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide Detection.
        /// </summary>
        public static string HideDetection {
            get {
                return ResourceManager.GetString("HideDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide Developer Tools.
        /// </summary>
        public static string HideDeveloperTools {
            get {
                return ResourceManager.GetString("HideDeveloperTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Hide Window.
        /// </summary>
        public static string HideWindow {
            get {
                return ResourceManager.GetString("HideWindow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Html.
        /// </summary>
        public static string Html {
            get {
                return ResourceManager.GetString("Html", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a iFrame.
        /// </summary>
        public static string iFrame {
            get {
                return ResourceManager.GetString("iFrame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Image to Text.
        /// </summary>
        public static string ImageToText {
            get {
                return ResourceManager.GetString("ImageToText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Keyboard.
        /// </summary>
        public static string Keyboard {
            get {
                return ResourceManager.GetString("Keyboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key Down.
        /// </summary>
        public static string KeyDown {
            get {
                return ResourceManager.GetString("KeyDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Key Up.
        /// </summary>
        public static string KeyUp {
            get {
                return ResourceManager.GetString("KeyUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Language.
        /// </summary>
        public static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Link.
        /// </summary>
        public static string Link {
            get {
                return ResourceManager.GetString("Link", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a List.
        /// </summary>
        public static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Load Html.
        /// </summary>
        public static string LoadHtml {
            get {
                return ResourceManager.GetString("LoadHtml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Lock WorkStation.
        /// </summary>
        public static string LockWorkStation {
            get {
                return ResourceManager.GetString("LockWorkStation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log.
        /// </summary>
        public static string Log {
            get {
                return ResourceManager.GetString("Log", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Login successful.
        /// </summary>
        public static string LoginSuccessful {
            get {
                return ResourceManager.GetString("LoginSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Log Off.
        /// </summary>
        public static string LogOff {
            get {
                return ResourceManager.GetString("LogOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Logout successful.
        /// </summary>
        public static string LogoutSuccessful {
            get {
                return ResourceManager.GetString("LogoutSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JS Macro run completed..
        /// </summary>
        public static string MacroComplete {
            get {
                return ResourceManager.GetString("MacroComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Accounts.
        /// </summary>
        public static string ManageAccounts {
            get {
                return ResourceManager.GetString("ManageAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Connections.
        /// </summary>
        public static string ManageConnections {
            get {
                return ResourceManager.GetString("ManageConnections", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Emails.
        /// </summary>
        public static string ManageEmails {
            get {
                return ResourceManager.GetString("ManageEmails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manager.
        /// </summary>
        public static string Manager {
            get {
                return ResourceManager.GetString("Manager", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Roles.
        /// </summary>
        public static string ManageRoles {
            get {
                return ResourceManager.GetString("ManageRoles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Manage Users.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Message.
        /// </summary>
        public static string Message {
            get {
                return ResourceManager.GetString("Message", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse.
        /// </summary>
        public static string Mouse {
            get {
                return ResourceManager.GetString("Mouse", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Click.
        /// </summary>
        public static string MouseClick {
            get {
                return ResourceManager.GetString("MouseClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Double Click.
        /// </summary>
        public static string MouseDoubleClick {
            get {
                return ResourceManager.GetString("MouseDoubleClick", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Down.
        /// </summary>
        public static string MouseDown {
            get {
                return ResourceManager.GetString("MouseDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Move.
        /// </summary>
        public static string MouseMove {
            get {
                return ResourceManager.GetString("MouseMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Up.
        /// </summary>
        public static string MouseUp {
            get {
                return ResourceManager.GetString("MouseUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Mouse Scroll.
        /// </summary>
        public static string MouseWheel {
            get {
                return ResourceManager.GetString("MouseWheel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a The Name you enter exists, please enter another one.
        /// </summary>
        public static string NameExists {
            get {
                return ResourceManager.GetString("NameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your Name.
        /// </summary>
        public static string NameRequired {
            get {
                return ResourceManager.GetString("NameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New.
        /// </summary>
        public static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Download.
        /// </summary>
        public static string NewDownload {
            get {
                return ResourceManager.GetString("NewDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Password and Confirm not the same.
        /// </summary>
        public static string NewPasswordAndConfirmNotTheSame {
            get {
                return ResourceManager.GetString("NewPasswordAndConfirmNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter new Password.
        /// </summary>
        public static string NewPasswordRequire {
            get {
                return ResourceManager.GetString("NewPasswordRequire", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Script.
        /// </summary>
        public static string NewScript {
            get {
                return ResourceManager.GetString("NewScript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Tab.
        /// </summary>
        public static string NewTab {
            get {
                return ResourceManager.GetString("NewTab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New template.
        /// </summary>
        public static string NewTemplate {
            get {
                return ResourceManager.GetString("NewTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a New Version of Software Release.
        /// </summary>
        public static string NewVersion {
            get {
                return ResourceManager.GetString("NewVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter number for this field.
        /// </summary>
        public static string NotNumber {
            get {
                return ResourceManager.GetString("NotNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OCR.
        /// </summary>
        public static string OCR {
            get {
                return ResourceManager.GetString("OCR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a OK.
        /// </summary>
        public static string OK {
            get {
                return ResourceManager.GetString("OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Old Password not correct.
        /// </summary>
        public static string OldPasswordIncorrect {
            get {
                return ResourceManager.GetString("OldPasswordIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Your version currently up to date.
        /// </summary>
        public static string OldVersion {
            get {
                return ResourceManager.GetString("OldVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open Explore.
        /// </summary>
        public static string OpenExplore {
            get {
                return ResourceManager.GetString("OpenExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can not open file, error: {0}.
        /// </summary>
        public static string OpenFileError {
            get {
                return ResourceManager.GetString("OpenFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open a script file..
        /// </summary>
        public static string OpenScriptTitle {
            get {
                return ResourceManager.GetString("OpenScriptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Open a template file..
        /// </summary>
        public static string OpenTemplateTitle {
            get {
                return ResourceManager.GetString("OpenTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Password and Confirm not the same.
        /// </summary>
        public static string PasswordAndConfirmNotTheSame {
            get {
                return ResourceManager.GetString("PasswordAndConfirmNotTheSame", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your Password.
        /// </summary>
        public static string PasswordRequired {
            get {
                return ResourceManager.GetString("PasswordRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause.
        /// </summary>
        public static string Pause {
            get {
                return ResourceManager.GetString("Pause", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Pause All.
        /// </summary>
        public static string PauseAll {
            get {
                return ResourceManager.GetString("PauseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Port.
        /// </summary>
        public static string Port {
            get {
                return ResourceManager.GetString("Port", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Preview.
        /// </summary>
        public static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Private Key.
        /// </summary>
        public static string PrivateKey {
            get {
                return ResourceManager.GetString("PrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Provider.
        /// </summary>
        public static string Provider {
            get {
                return ResourceManager.GetString("Provider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Public Key.
        /// </summary>
        public static string PublicKey {
            get {
                return ResourceManager.GetString("PublicKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read.
        /// </summary>
        public static string Read {
            get {
                return ResourceManager.GetString("Read", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read Cell Excel.
        /// </summary>
        public static string ReadCellExcel {
            get {
                return ResourceManager.GetString("ReadCellExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Read Excel.
        /// </summary>
        public static string ReadExcel {
            get {
                return ResourceManager.GetString("ReadExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a File readonly, can&apos;t save.
        /// </summary>
        public static string ReadOnlyFile {
            get {
                return ResourceManager.GetString("ReadOnlyFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reboot.
        /// </summary>
        public static string Reboot {
            get {
                return ResourceManager.GetString("Reboot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Record.
        /// </summary>
        public static string Record {
            get {
                return ResourceManager.GetString("Record", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Register Successful.
        /// </summary>
        public static string RegisterSuccessful {
            get {
                return ResourceManager.GetString("RegisterSuccessful", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Reload.
        /// </summary>
        public static string Reload {
            get {
                return ResourceManager.GetString("Reload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove File.
        /// </summary>
        public static string RemoveFile {
            get {
                return ResourceManager.GetString("RemoveFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Remove Folder.
        /// </summary>
        public static string RemoveFolder {
            get {
                return ResourceManager.GetString("RemoveFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Repeat Element.
        /// </summary>
        public static string RepeatElement {
            get {
                return ResourceManager.GetString("RepeatElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Replace Microsoft Word.
        /// </summary>
        public static string ReplaceMSWord {
            get {
                return ResourceManager.GetString("ReplaceMSWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select row to delete.
        /// </summary>
        public static string RowNotSelectedForDelete {
            get {
                return ResourceManager.GetString("RowNotSelectedForDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please select row to update.
        /// </summary>
        public static string RowNotSelectedForUpdate {
            get {
                return ResourceManager.GetString("RowNotSelectedForUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Run.
        /// </summary>
        public static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JS Macro running.....
        /// </summary>
        public static string RunBegin {
            get {
                return ResourceManager.GetString("RunBegin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Run Command.
        /// </summary>
        public static string RunCommand {
            get {
                return ResourceManager.GetString("RunCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a JS Macro run completed..
        /// </summary>
        public static string RunComplete {
            get {
                return ResourceManager.GetString("RunComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save As.
        /// </summary>
        public static string SaveAs {
            get {
                return ResourceManager.GetString("SaveAs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saved.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Can not save file, error: {0}.
        /// </summary>
        public static string SaveFileError {
            get {
                return ResourceManager.GetString("SaveFileError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save Image From Element.
        /// </summary>
        public static string SaveImageFromElement {
            get {
                return ResourceManager.GetString("SaveImageFromElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save a script file..
        /// </summary>
        public static string SaveScriptTitle {
            get {
                return ResourceManager.GetString("SaveScriptTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Save a template file..
        /// </summary>
        public static string SaveTemplateTitle {
            get {
                return ResourceManager.GetString("SaveTemplateTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Saving....
        /// </summary>
        public static string Saving {
            get {
                return ResourceManager.GetString("Saving", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scroll To.
        /// </summary>
        public static string ScrollTo {
            get {
                return ResourceManager.GetString("ScrollTo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Scroll To View.
        /// </summary>
        public static string ScrollToView {
            get {
                return ResourceManager.GetString("ScrollToView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Send Email.
        /// </summary>
        public static string SendEmail {
            get {
                return ResourceManager.GetString("SendEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Server.
        /// </summary>
        public static string Server {
            get {
                return ResourceManager.GetString("Server", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Set Control Text.
        /// </summary>
        public static string SetControlText {
            get {
                return ResourceManager.GetString("SetControlText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show code.
        /// </summary>
        public static string ShowCode {
            get {
                return ResourceManager.GetString("ShowCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Detection.
        /// </summary>
        public static string ShowDetection {
            get {
                return ResourceManager.GetString("ShowDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Developer Tools.
        /// </summary>
        public static string ShowDeveloperTools {
            get {
                return ResourceManager.GetString("ShowDeveloperTools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show/Hide Detection.
        /// </summary>
        public static string ShowHideDetection {
            get {
                return ResourceManager.GetString("ShowHideDetection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show/Hide Developer.
        /// </summary>
        public static string ShowHideDeveloper {
            get {
                return ResourceManager.GetString("ShowHideDeveloper", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enable/Disable Flash.
        /// </summary>
        public static string ShowImages {
            get {
                return ResourceManager.GetString("ShowImages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show in Explore.
        /// </summary>
        public static string ShowInExplore {
            get {
                return ResourceManager.GetString("ShowInExplore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show in tree.
        /// </summary>
        public static string ShowInTree {
            get {
                return ResourceManager.GetString("ShowInTree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Show Picture.
        /// </summary>
        public static string ShowPicture {
            get {
                return ResourceManager.GetString("ShowPicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Shutdown.
        /// </summary>
        public static string ShutDown {
            get {
                return ResourceManager.GetString("ShutDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sleep.
        /// </summary>
        public static string Sleep {
            get {
                return ResourceManager.GetString("Sleep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Spanish.
        /// </summary>
        public static string Spanish {
            get {
                return ResourceManager.GetString("Spanish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Sql.
        /// </summary>
        public static string Sql {
            get {
                return ResourceManager.GetString("Sql", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Src.
        /// </summary>
        public static string Src {
            get {
                return ResourceManager.GetString("Src", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a StandBy.
        /// </summary>
        public static string StandBy {
            get {
                return ResourceManager.GetString("StandBy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start.
        /// </summary>
        public static string Start {
            get {
                return ResourceManager.GetString("Start", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Start Regconization.
        /// </summary>
        public static string StartRegconization {
            get {
                return ResourceManager.GetString("StartRegconization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop.
        /// </summary>
        public static string Stop {
            get {
                return ResourceManager.GetString("Stop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Stop Regconization.
        /// </summary>
        public static string StopRegconization {
            get {
                return ResourceManager.GetString("StopRegconization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Take SnapShot.
        /// </summary>
        public static string TakeSnapShot {
            get {
                return ResourceManager.GetString("TakeSnapShot", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Template.
        /// </summary>
        public static string Template {
            get {
                return ResourceManager.GetString("Template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text.
        /// </summary>
        public static string Text {
            get {
                return ResourceManager.GetString("Text", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Textbox.
        /// </summary>
        public static string Textbox {
            get {
                return ResourceManager.GetString("Textbox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text to Json.
        /// </summary>
        public static string TextToJson {
            get {
                return ResourceManager.GetString("TextToJson", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Text To Xml.
        /// </summary>
        public static string TextToXml {
            get {
                return ResourceManager.GetString("TextToXml", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Title.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a To Object.
        /// </summary>
        public static string ToObject {
            get {
                return ResourceManager.GetString("ToObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Tools.
        /// </summary>
        public static string Tools {
            get {
                return ResourceManager.GetString("Tools", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unicode script file (*.script)|*.script.
        /// </summary>
        public static string UnicodeScriptFile {
            get {
                return ResourceManager.GetString("UnicodeScriptFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Unicode template file (*.template)|*.template.
        /// </summary>
        public static string UnicodeTemplateFile {
            get {
                return ResourceManager.GetString("UnicodeTemplateFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Update successful.
        /// </summary>
        public static string UpdateSuccess {
            get {
                return ResourceManager.GetString("UpdateSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Url.
        /// </summary>
        public static string Url {
            get {
                return ResourceManager.GetString("Url", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User Account Update.
        /// </summary>
        public static string UserAccountUpdate {
            get {
                return ResourceManager.GetString("UserAccountUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User-Agent.
        /// </summary>
        public static string UserAgent {
            get {
                return ResourceManager.GetString("UserAgent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Enter User-Agent string.
        /// </summary>
        public static string UserAgentString {
            get {
                return ResourceManager.GetString("UserAgentString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Username.
        /// </summary>
        public static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Please enter your Username.
        /// </summary>
        public static string UsernameRequired {
            get {
                return ResourceManager.GetString("UsernameRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a User not exists.
        /// </summary>
        public static string UserNotExists {
            get {
                return ResourceManager.GetString("UserNotExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Utility.
        /// </summary>
        public static string Utility {
            get {
                return ResourceManager.GetString("Utility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Version.
        /// </summary>
        public static string Version {
            get {
                return ResourceManager.GetString("Version", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Website.
        /// </summary>
        public static string Website {
            get {
                return ResourceManager.GetString("Website", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write Cell Excel.
        /// </summary>
        public static string WriteCellExcel {
            get {
                return ResourceManager.GetString("WriteCellExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Busca una cadena traducida similar a Write Excel.
        /// </summary>
        public static string WriteExcel {
            get {
                return ResourceManager.GetString("WriteExcel", resourceCulture);
            }
        }
    }
}
