//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FSTests.ServiceReference2 {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://febrersoftware.com", ConfigurationName="ServiceReference2.AdminWSSoap")]
    public interface AdminWSSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento TablasResult del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Tablas", ReplyAction="*")]
        FSTests.ServiceReference2.TablasResponse Tablas(FSTests.ServiceReference2.TablasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Tablas", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.TablasResponse> TablasAsync(FSTests.ServiceReference2.TablasRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreTabla del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/EsquemaTabla", ReplyAction="*")]
        FSTests.ServiceReference2.EsquemaTablaResponse EsquemaTabla(FSTests.ServiceReference2.EsquemaTablaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/EsquemaTabla", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.EsquemaTablaResponse> EsquemaTablaAsync(FSTests.ServiceReference2.EsquemaTablaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento nombreTabla del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Tabla", ReplyAction="*")]
        FSTests.ServiceReference2.TablaResponse Tabla(FSTests.ServiceReference2.TablaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Tabla", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.TablaResponse> TablaAsync(FSTests.ServiceReference2.TablaRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento sql del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Selection", ReplyAction="*")]
        FSTests.ServiceReference2.SelectionResponse Selection(FSTests.ServiceReference2.SelectionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Selection", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.SelectionResponse> SelectionAsync(FSTests.ServiceReference2.SelectionRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento UsuariosResult del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Usuarios", ReplyAction="*")]
        FSTests.ServiceReference2.UsuariosResponse Usuarios(FSTests.ServiceReference2.UsuariosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Usuarios", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.UsuariosResponse> UsuariosAsync(FSTests.ServiceReference2.UsuariosRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ArticulosResult del espacio de nombres http://febrersoftware.com no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Articulos", ReplyAction="*")]
        FSTests.ServiceReference2.ArticulosResponse Articulos(FSTests.ServiceReference2.ArticulosRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://febrersoftware.com/Articulos", ReplyAction="*")]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.ArticulosResponse> ArticulosAsync(FSTests.ServiceReference2.ArticulosRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tablas", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.TablasRequestBody Body;
        
        public TablasRequest() {
        }
        
        public TablasRequest(FSTests.ServiceReference2.TablasRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class TablasRequestBody {
        
        public TablasRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TablasResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.TablasResponseBody Body;
        
        public TablasResponse() {
        }
        
        public TablasResponse(FSTests.ServiceReference2.TablasResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class TablasResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TablasResult;
        
        public TablasResponseBody() {
        }
        
        public TablasResponseBody(string TablasResult) {
            this.TablasResult = TablasResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsquemaTablaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsquemaTabla", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.EsquemaTablaRequestBody Body;
        
        public EsquemaTablaRequest() {
        }
        
        public EsquemaTablaRequest(FSTests.ServiceReference2.EsquemaTablaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class EsquemaTablaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreTabla;
        
        public EsquemaTablaRequestBody() {
        }
        
        public EsquemaTablaRequestBody(string nombreTabla) {
            this.nombreTabla = nombreTabla;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class EsquemaTablaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="EsquemaTablaResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.EsquemaTablaResponseBody Body;
        
        public EsquemaTablaResponse() {
        }
        
        public EsquemaTablaResponse(FSTests.ServiceReference2.EsquemaTablaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class EsquemaTablaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string EsquemaTablaResult;
        
        public EsquemaTablaResponseBody() {
        }
        
        public EsquemaTablaResponseBody(string EsquemaTablaResult) {
            this.EsquemaTablaResult = EsquemaTablaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Tabla", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.TablaRequestBody Body;
        
        public TablaRequest() {
        }
        
        public TablaRequest(FSTests.ServiceReference2.TablaRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class TablaRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string nombreTabla;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int page;
        
        public TablaRequestBody() {
        }
        
        public TablaRequestBody(string nombreTabla, int page) {
            this.nombreTabla = nombreTabla;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class TablaResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="TablaResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.TablaResponseBody Body;
        
        public TablaResponse() {
        }
        
        public TablaResponse(FSTests.ServiceReference2.TablaResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class TablaResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string TablaResult;
        
        public TablaResponseBody() {
        }
        
        public TablaResponseBody(string TablaResult) {
            this.TablaResult = TablaResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Selection", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.SelectionRequestBody Body;
        
        public SelectionRequest() {
        }
        
        public SelectionRequest(FSTests.ServiceReference2.SelectionRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class SelectionRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string sql;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public int page;
        
        public SelectionRequestBody() {
        }
        
        public SelectionRequestBody(string sql, int page) {
            this.sql = sql;
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SelectionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SelectionResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.SelectionResponseBody Body;
        
        public SelectionResponse() {
        }
        
        public SelectionResponse(FSTests.ServiceReference2.SelectionResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class SelectionResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string SelectionResult;
        
        public SelectionResponseBody() {
        }
        
        public SelectionResponseBody(string SelectionResult) {
            this.SelectionResult = SelectionResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuariosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Usuarios", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.UsuariosRequestBody Body;
        
        public UsuariosRequest() {
        }
        
        public UsuariosRequest(FSTests.ServiceReference2.UsuariosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class UsuariosRequestBody {
        
        public UsuariosRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UsuariosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UsuariosResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.UsuariosResponseBody Body;
        
        public UsuariosResponse() {
        }
        
        public UsuariosResponse(FSTests.ServiceReference2.UsuariosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class UsuariosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UsuariosResult;
        
        public UsuariosResponseBody() {
        }
        
        public UsuariosResponseBody(string UsuariosResult) {
            this.UsuariosResult = UsuariosResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ArticulosRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="Articulos", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.ArticulosRequestBody Body;
        
        public ArticulosRequest() {
        }
        
        public ArticulosRequest(FSTests.ServiceReference2.ArticulosRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class ArticulosRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int page;
        
        public ArticulosRequestBody() {
        }
        
        public ArticulosRequestBody(int page) {
            this.page = page;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ArticulosResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ArticulosResponse", Namespace="http://febrersoftware.com", Order=0)]
        public FSTests.ServiceReference2.ArticulosResponseBody Body;
        
        public ArticulosResponse() {
        }
        
        public ArticulosResponse(FSTests.ServiceReference2.ArticulosResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://febrersoftware.com")]
    public partial class ArticulosResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string ArticulosResult;
        
        public ArticulosResponseBody() {
        }
        
        public ArticulosResponseBody(string ArticulosResult) {
            this.ArticulosResult = ArticulosResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AdminWSSoapChannel : FSTests.ServiceReference2.AdminWSSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AdminWSSoapClient : System.ServiceModel.ClientBase<FSTests.ServiceReference2.AdminWSSoap>, FSTests.ServiceReference2.AdminWSSoap {
        
        public AdminWSSoapClient() {
        }
        
        public AdminWSSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AdminWSSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminWSSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AdminWSSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference2.TablasResponse FSTests.ServiceReference2.AdminWSSoap.Tablas(FSTests.ServiceReference2.TablasRequest request) {
            return base.Channel.Tablas(request);
        }
        
        public string Tablas() {
            FSTests.ServiceReference2.TablasRequest inValue = new FSTests.ServiceReference2.TablasRequest();
            inValue.Body = new FSTests.ServiceReference2.TablasRequestBody();
            FSTests.ServiceReference2.TablasResponse retVal = ((FSTests.ServiceReference2.AdminWSSoap)(this)).Tablas(inValue);
            return retVal.Body.TablasResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.TablasResponse> FSTests.ServiceReference2.AdminWSSoap.TablasAsync(FSTests.ServiceReference2.TablasRequest request) {
            return base.Channel.TablasAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference2.TablasResponse> TablasAsync() {
            FSTests.ServiceReference2.TablasRequest inValue = new FSTests.ServiceReference2.TablasRequest();
            inValue.Body = new FSTests.ServiceReference2.TablasRequestBody();
            return ((FSTests.ServiceReference2.AdminWSSoap)(this)).TablasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference2.EsquemaTablaResponse FSTests.ServiceReference2.AdminWSSoap.EsquemaTabla(FSTests.ServiceReference2.EsquemaTablaRequest request) {
            return base.Channel.EsquemaTabla(request);
        }
        
        public string EsquemaTabla(string nombreTabla) {
            FSTests.ServiceReference2.EsquemaTablaRequest inValue = new FSTests.ServiceReference2.EsquemaTablaRequest();
            inValue.Body = new FSTests.ServiceReference2.EsquemaTablaRequestBody();
            inValue.Body.nombreTabla = nombreTabla;
            FSTests.ServiceReference2.EsquemaTablaResponse retVal = ((FSTests.ServiceReference2.AdminWSSoap)(this)).EsquemaTabla(inValue);
            return retVal.Body.EsquemaTablaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.EsquemaTablaResponse> FSTests.ServiceReference2.AdminWSSoap.EsquemaTablaAsync(FSTests.ServiceReference2.EsquemaTablaRequest request) {
            return base.Channel.EsquemaTablaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference2.EsquemaTablaResponse> EsquemaTablaAsync(string nombreTabla) {
            FSTests.ServiceReference2.EsquemaTablaRequest inValue = new FSTests.ServiceReference2.EsquemaTablaRequest();
            inValue.Body = new FSTests.ServiceReference2.EsquemaTablaRequestBody();
            inValue.Body.nombreTabla = nombreTabla;
            return ((FSTests.ServiceReference2.AdminWSSoap)(this)).EsquemaTablaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference2.TablaResponse FSTests.ServiceReference2.AdminWSSoap.Tabla(FSTests.ServiceReference2.TablaRequest request) {
            return base.Channel.Tabla(request);
        }
        
        public string Tabla(string nombreTabla, int page) {
            FSTests.ServiceReference2.TablaRequest inValue = new FSTests.ServiceReference2.TablaRequest();
            inValue.Body = new FSTests.ServiceReference2.TablaRequestBody();
            inValue.Body.nombreTabla = nombreTabla;
            inValue.Body.page = page;
            FSTests.ServiceReference2.TablaResponse retVal = ((FSTests.ServiceReference2.AdminWSSoap)(this)).Tabla(inValue);
            return retVal.Body.TablaResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.TablaResponse> FSTests.ServiceReference2.AdminWSSoap.TablaAsync(FSTests.ServiceReference2.TablaRequest request) {
            return base.Channel.TablaAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference2.TablaResponse> TablaAsync(string nombreTabla, int page) {
            FSTests.ServiceReference2.TablaRequest inValue = new FSTests.ServiceReference2.TablaRequest();
            inValue.Body = new FSTests.ServiceReference2.TablaRequestBody();
            inValue.Body.nombreTabla = nombreTabla;
            inValue.Body.page = page;
            return ((FSTests.ServiceReference2.AdminWSSoap)(this)).TablaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference2.SelectionResponse FSTests.ServiceReference2.AdminWSSoap.Selection(FSTests.ServiceReference2.SelectionRequest request) {
            return base.Channel.Selection(request);
        }
        
        public string Selection(string sql, int page) {
            FSTests.ServiceReference2.SelectionRequest inValue = new FSTests.ServiceReference2.SelectionRequest();
            inValue.Body = new FSTests.ServiceReference2.SelectionRequestBody();
            inValue.Body.sql = sql;
            inValue.Body.page = page;
            FSTests.ServiceReference2.SelectionResponse retVal = ((FSTests.ServiceReference2.AdminWSSoap)(this)).Selection(inValue);
            return retVal.Body.SelectionResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.SelectionResponse> FSTests.ServiceReference2.AdminWSSoap.SelectionAsync(FSTests.ServiceReference2.SelectionRequest request) {
            return base.Channel.SelectionAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference2.SelectionResponse> SelectionAsync(string sql, int page) {
            FSTests.ServiceReference2.SelectionRequest inValue = new FSTests.ServiceReference2.SelectionRequest();
            inValue.Body = new FSTests.ServiceReference2.SelectionRequestBody();
            inValue.Body.sql = sql;
            inValue.Body.page = page;
            return ((FSTests.ServiceReference2.AdminWSSoap)(this)).SelectionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference2.UsuariosResponse FSTests.ServiceReference2.AdminWSSoap.Usuarios(FSTests.ServiceReference2.UsuariosRequest request) {
            return base.Channel.Usuarios(request);
        }
        
        public string Usuarios() {
            FSTests.ServiceReference2.UsuariosRequest inValue = new FSTests.ServiceReference2.UsuariosRequest();
            inValue.Body = new FSTests.ServiceReference2.UsuariosRequestBody();
            FSTests.ServiceReference2.UsuariosResponse retVal = ((FSTests.ServiceReference2.AdminWSSoap)(this)).Usuarios(inValue);
            return retVal.Body.UsuariosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.UsuariosResponse> FSTests.ServiceReference2.AdminWSSoap.UsuariosAsync(FSTests.ServiceReference2.UsuariosRequest request) {
            return base.Channel.UsuariosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference2.UsuariosResponse> UsuariosAsync() {
            FSTests.ServiceReference2.UsuariosRequest inValue = new FSTests.ServiceReference2.UsuariosRequest();
            inValue.Body = new FSTests.ServiceReference2.UsuariosRequestBody();
            return ((FSTests.ServiceReference2.AdminWSSoap)(this)).UsuariosAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FSTests.ServiceReference2.ArticulosResponse FSTests.ServiceReference2.AdminWSSoap.Articulos(FSTests.ServiceReference2.ArticulosRequest request) {
            return base.Channel.Articulos(request);
        }
        
        public string Articulos(int page) {
            FSTests.ServiceReference2.ArticulosRequest inValue = new FSTests.ServiceReference2.ArticulosRequest();
            inValue.Body = new FSTests.ServiceReference2.ArticulosRequestBody();
            inValue.Body.page = page;
            FSTests.ServiceReference2.ArticulosResponse retVal = ((FSTests.ServiceReference2.AdminWSSoap)(this)).Articulos(inValue);
            return retVal.Body.ArticulosResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<FSTests.ServiceReference2.ArticulosResponse> FSTests.ServiceReference2.AdminWSSoap.ArticulosAsync(FSTests.ServiceReference2.ArticulosRequest request) {
            return base.Channel.ArticulosAsync(request);
        }
        
        public System.Threading.Tasks.Task<FSTests.ServiceReference2.ArticulosResponse> ArticulosAsync(int page) {
            FSTests.ServiceReference2.ArticulosRequest inValue = new FSTests.ServiceReference2.ArticulosRequest();
            inValue.Body = new FSTests.ServiceReference2.ArticulosRequestBody();
            inValue.Body.page = page;
            return ((FSTests.ServiceReference2.AdminWSSoap)(this)).ArticulosAsync(inValue);
        }
    }
}
