//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Microsoft.VSDesigner generó automáticamente este código fuente, versión=4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FSTests.com.febrersoftware.www1 {
    using System.Diagnostics;
    using System;
    using System.Xml.Serialization;
    using System.ComponentModel;
    using System.Web.Services.Protocols;
    using System.Web.Services;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="AdminWSSoap", Namespace="http://febrersoftware.com")]
    public partial class AdminWS : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback TablasOperationCompleted;
        
        private System.Threading.SendOrPostCallback EsquemaTablaOperationCompleted;
        
        private System.Threading.SendOrPostCallback TablaOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectionOperationCompleted;
        
        private System.Threading.SendOrPostCallback UsuariosOperationCompleted;
        
        private System.Threading.SendOrPostCallback ArticulosOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public AdminWS() {
            this.Url = global::FSTests.Properties.Settings.Default.FSTests_com_febrersoftware_www1_AdminWS;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event TablasCompletedEventHandler TablasCompleted;
        
        /// <remarks/>
        public event EsquemaTablaCompletedEventHandler EsquemaTablaCompleted;
        
        /// <remarks/>
        public event TablaCompletedEventHandler TablaCompleted;
        
        /// <remarks/>
        public event SelectionCompletedEventHandler SelectionCompleted;
        
        /// <remarks/>
        public event UsuariosCompletedEventHandler UsuariosCompleted;
        
        /// <remarks/>
        public event ArticulosCompletedEventHandler ArticulosCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://febrersoftware.com/Tablas", RequestNamespace="http://febrersoftware.com", ResponseNamespace="http://febrersoftware.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Tablas() {
            object[] results = this.Invoke("Tablas", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TablasAsync() {
            this.TablasAsync(null);
        }
        
        /// <remarks/>
        public void TablasAsync(object userState) {
            if ((this.TablasOperationCompleted == null)) {
                this.TablasOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTablasOperationCompleted);
            }
            this.InvokeAsync("Tablas", new object[0], this.TablasOperationCompleted, userState);
        }
        
        private void OnTablasOperationCompleted(object arg) {
            if ((this.TablasCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TablasCompleted(this, new TablasCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://febrersoftware.com/EsquemaTabla", RequestNamespace="http://febrersoftware.com", ResponseNamespace="http://febrersoftware.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string EsquemaTabla(string nombreTabla) {
            object[] results = this.Invoke("EsquemaTabla", new object[] {
                        nombreTabla});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void EsquemaTablaAsync(string nombreTabla) {
            this.EsquemaTablaAsync(nombreTabla, null);
        }
        
        /// <remarks/>
        public void EsquemaTablaAsync(string nombreTabla, object userState) {
            if ((this.EsquemaTablaOperationCompleted == null)) {
                this.EsquemaTablaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnEsquemaTablaOperationCompleted);
            }
            this.InvokeAsync("EsquemaTabla", new object[] {
                        nombreTabla}, this.EsquemaTablaOperationCompleted, userState);
        }
        
        private void OnEsquemaTablaOperationCompleted(object arg) {
            if ((this.EsquemaTablaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.EsquemaTablaCompleted(this, new EsquemaTablaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://febrersoftware.com/Tabla", RequestNamespace="http://febrersoftware.com", ResponseNamespace="http://febrersoftware.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Tabla(string nombreTabla, int page) {
            object[] results = this.Invoke("Tabla", new object[] {
                        nombreTabla,
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void TablaAsync(string nombreTabla, int page) {
            this.TablaAsync(nombreTabla, page, null);
        }
        
        /// <remarks/>
        public void TablaAsync(string nombreTabla, int page, object userState) {
            if ((this.TablaOperationCompleted == null)) {
                this.TablaOperationCompleted = new System.Threading.SendOrPostCallback(this.OnTablaOperationCompleted);
            }
            this.InvokeAsync("Tabla", new object[] {
                        nombreTabla,
                        page}, this.TablaOperationCompleted, userState);
        }
        
        private void OnTablaOperationCompleted(object arg) {
            if ((this.TablaCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.TablaCompleted(this, new TablaCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://febrersoftware.com/Selection", RequestNamespace="http://febrersoftware.com", ResponseNamespace="http://febrersoftware.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Selection(string sql, int page) {
            object[] results = this.Invoke("Selection", new object[] {
                        sql,
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelectionAsync(string sql, int page) {
            this.SelectionAsync(sql, page, null);
        }
        
        /// <remarks/>
        public void SelectionAsync(string sql, int page, object userState) {
            if ((this.SelectionOperationCompleted == null)) {
                this.SelectionOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectionOperationCompleted);
            }
            this.InvokeAsync("Selection", new object[] {
                        sql,
                        page}, this.SelectionOperationCompleted, userState);
        }
        
        private void OnSelectionOperationCompleted(object arg) {
            if ((this.SelectionCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectionCompleted(this, new SelectionCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://febrersoftware.com/Usuarios", RequestNamespace="http://febrersoftware.com", ResponseNamespace="http://febrersoftware.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Usuarios() {
            object[] results = this.Invoke("Usuarios", new object[0]);
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UsuariosAsync() {
            this.UsuariosAsync(null);
        }
        
        /// <remarks/>
        public void UsuariosAsync(object userState) {
            if ((this.UsuariosOperationCompleted == null)) {
                this.UsuariosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUsuariosOperationCompleted);
            }
            this.InvokeAsync("Usuarios", new object[0], this.UsuariosOperationCompleted, userState);
        }
        
        private void OnUsuariosOperationCompleted(object arg) {
            if ((this.UsuariosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UsuariosCompleted(this, new UsuariosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://febrersoftware.com/Articulos", RequestNamespace="http://febrersoftware.com", ResponseNamespace="http://febrersoftware.com", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Articulos(int page) {
            object[] results = this.Invoke("Articulos", new object[] {
                        page});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void ArticulosAsync(int page) {
            this.ArticulosAsync(page, null);
        }
        
        /// <remarks/>
        public void ArticulosAsync(int page, object userState) {
            if ((this.ArticulosOperationCompleted == null)) {
                this.ArticulosOperationCompleted = new System.Threading.SendOrPostCallback(this.OnArticulosOperationCompleted);
            }
            this.InvokeAsync("Articulos", new object[] {
                        page}, this.ArticulosOperationCompleted, userState);
        }
        
        private void OnArticulosOperationCompleted(object arg) {
            if ((this.ArticulosCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ArticulosCompleted(this, new ArticulosCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TablasCompletedEventHandler(object sender, TablasCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TablasCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TablasCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void EsquemaTablaCompletedEventHandler(object sender, EsquemaTablaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class EsquemaTablaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal EsquemaTablaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void TablaCompletedEventHandler(object sender, TablaCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class TablaCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal TablaCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void SelectionCompletedEventHandler(object sender, SelectionCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectionCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectionCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void UsuariosCompletedEventHandler(object sender, UsuariosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UsuariosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UsuariosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    public delegate void ArticulosCompletedEventHandler(object sender, ArticulosCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.9037.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class ArticulosCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal ArticulosCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591